// Export Service for PDF and PPTX Generation
import { jsPDF } from 'jspdf';
import pptxgen from 'pptxgenjs';

// 1. Export Business Plan as PDF
export function exportBusinessPlanPDF(startupTitle, plan) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const primaryColor = [12, 74, 110]; // slate-900 / dark blue
  const secondaryColor = [79, 70, 229]; // indigo-600

  // Cover Page
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 297, 'F');

  // Decorative diagonal accent
  doc.setFillColor(...secondaryColor);
  doc.triangle(0, 297, 210, 297, 210, 220, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.text('STARTUP BUSINESS PLAN', 20, 100);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(20);
  doc.text(startupTitle.toUpperCase(), 20, 115);

  doc.setFontSize(12);
  doc.setTextColor(200, 200, 200);
  doc.text(`Generated by AI Startup Mentor`, 20, 260);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 268);

  // Content Pages
  const sections = [
    { title: '1. Executive Summary', content: plan.executiveSummary },
    { title: '2. Problem Statement', content: plan.problemStatement },
    { title: '3. Proposed Solution', content: plan.solution },
    { title: '4. Target Market & Audience', content: plan.targetMarket },
    { title: '5. Revenue & Monetization Model', content: plan.revenueModel },
    { title: '6. Marketing & Growth Strategy', content: plan.marketingStrategy },
    { title: '7. Operations Plan', content: plan.operationsPlan },
    { title: '8. Financial Forecasts & Funding Plan', content: plan.financialPlan }
  ];

  sections.forEach((sec) => {
    doc.addPage();
    // Header
    doc.setFillColor(245, 247, 250);
    doc.rect(0, 0, 210, 25, 'F');
    doc.setDrawColor(220, 225, 230);
    doc.line(0, 25, 210, 25);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(100, 110, 120);
    doc.text(startupTitle.toUpperCase(), 20, 15);

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...primaryColor);
    doc.text(sec.title, 20, 45);

    // Divider line
    doc.setDrawColor(...secondaryColor);
    doc.setLineWidth(0.8);
    doc.line(20, 48, 60, 48);

    // Content text (wrapped)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(50, 60, 70);
    doc.setLineWidth(0.2);

    const splitText = doc.splitTextToSize(sec.content || 'Content not generated yet.', 170);
    doc.text(splitText, 20, 60);

    // Footer
    const totalPages = doc.internal.getNumberOfPages();
    doc.setFontSize(9);
    doc.setTextColor(150, 160, 170);
    doc.text(`Page ${totalPages}`, 180, 285);
  });

  doc.save(`${startupTitle.replace(/\s+/g, '_')}_Business_Plan.pdf`);
}

// 2. Export Pitch Deck as PDF
export function exportPitchDeckPDF(startupTitle, slides) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4' // 297mm x 210mm
  });

  const navyColor = [15, 23, 42]; // slate-900
  const blueColor = [59, 130, 246]; // blue-500

  slides.forEach((slide, index) => {
    if (index > 0) {
      doc.addPage();
    }

    // Modern Dark Theme Slides
    doc.setFillColor(...navyColor);
    doc.rect(0, 0, 297, 210, 'F');

    // Subtle side strip
    doc.setFillColor(...blueColor);
    doc.rect(0, 0, 8, 210, 'F');

    // Slide Number top right
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139);
    doc.text(`SLIDE ${slide.slideNumber || index + 1}`, 270, 20);

    // Slide Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text(slide.title, 25, 40);

    // Divider line
    doc.setFillColor(...blueColor);
    doc.rect(25, 46, 50, 2, 'F');

    // Slide Content Text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(226, 232, 240); // slate-200

    const contentLines = (slide.content || '').split('\n');
    let yPos = 65;
    contentLines.forEach(line => {
      const splitLine = doc.splitTextToSize(line, 240);
      doc.text(splitLine, 25, yPos);
      yPos += (splitLine.length * 8);
    });

    // Branding Footer
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`${startupTitle} | AI Investor Presentation`, 25, 195);
  });

  doc.save(`${startupTitle.replace(/\s+/g, '_')}_Pitch_Deck.pdf`);
}

// 3. Export Pitch Deck as PPTX
export function exportPitchDeckPPTX(startupTitle, slides) {
  let pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';

  const darkNavy = '0F172A'; // Slate-900
  const vibrantBlue = '3B82F6'; // Blue-500
  const slideText = 'E2E8F0'; // Slate-200

  slides.forEach((slide, index) => {
    let pptxSlide = pptx.addSlide();

    // Set background color
    pptxSlide.background = { fill: darkNavy };

    // Left accent bar
    pptxSlide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 0.2,
      h: 5.625,
      fill: { color: vibrantBlue }
    });

    // Slide Number (Top Right)
    pptxSlide.addText(`SLIDE ${slide.slideNumber || index + 1}`, {
      x: 11.5,
      y: 0.4,
      w: 1.5,
      h: 0.4,
      fontSize: 12,
      bold: true,
      color: '64748B',
      align: 'right',
      fontFace: 'Arial'
    });

    // Slide Title
    pptxSlide.addText(slide.title, {
      x: 0.8,
      y: 0.8,
      w: 9.0,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: 'FFFFFF',
      fontFace: 'Arial'
    });

    // Title underline
    pptxSlide.addShape(pptx.ShapeType.rect, {
      x: 0.8,
      y: 1.6,
      w: 2.0,
      h: 0.05,
      fill: { color: vibrantBlue }
    });

    // Slide Content (Bullet Lists)
    const contentText = slide.content || '';
    const items = contentText.split('\n').filter(line => line.trim().length > 0);

    // Format content nicely
    let yPos = 2.0;
    if (items.length > 0) {
      items.forEach(item => {
        // Clean item of bullet symbols (e.g. • or -) if it starts with them, as pptx will render bullets
        let cleaned = item.trim();
        if (cleaned.startsWith('•') || cleaned.startsWith('-')) {
          cleaned = cleaned.substring(1).trim();
        }

        pptxSlide.addText(cleaned, {
          x: 0.8,
          y: yPos,
          w: 11.0,
          h: 0.5,
          fontSize: 16,
          color: slideText,
          fontFace: 'Arial',
          bullet: true
        });
        yPos += 0.65;
      });
    } else {
      pptxSlide.addText("No content provided.", {
        x: 0.8,
        y: yPos,
        w: 11.0,
        h: 2.0,
        fontSize: 16,
        color: slideText,
        fontFace: 'Arial'
      });
    }

    // Footer
    pptxSlide.addText(`${startupTitle} | AI Pitch Presentation`, {
      x: 0.8,
      y: 5.0,
      w: 8.0,
      h: 0.3,
      fontSize: 10,
      color: '94A3B8',
      fontFace: 'Arial'
    });
  });

  pptx.writeFile({ fileName: `${startupTitle.replace(/\s+/g, '_')}_Pitch_Deck.pptx` });
}
